Repository MikuEngineering/missue-tracker-backend, pull requests merged in 2019-12, with the labels that each got.

#4 Create the schema Project
  src/app.module.ts
  src/projects/projects.entity.ts
  src/projects/projects.module.ts
  src/tags/tags.entity.ts
  src/tags/tags.module.ts
  src/users/users.entity.ts
Labels: enhancement

#5 Basic code for registering user
  src/users/dto/register_user.dto.ts
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
  src/users/users.module.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: enhancement

#6 Set default value of user schema
  src/users/users.entity.ts
Labels: enhancement

#7 Remove password in log
  src/users/users.controller.ts
Labels: bug

#8 Beautify codes of registering
  src/users/users.service.ts
Labels: enhancement

#10 Use passport to handle login
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/auth/dto/validate_user.dto.ts
  src/auth/local.strategy.ts
  src/session/session.controller.spec.ts
  src/session/session.controller.ts
  src/session/session.module.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: enhancement

#11 Make username unique
  src/users/users.entity.ts
Labels: bug

#12 Create an express-session for storing users' state
  package-lock.json
  package.json
  src/common/guards/authenticated.guard.ts
  src/common/guards/login.guard.ts
  src/main.ts
  src/session/session.controller.ts
  src/session/session.module.ts
  src/session/session.serializer.ts
  src/users/users.service.ts
Labels: enhancement

#14 Replace 4 spaces with 2 spaces for indention
  src/auth/auth.service.ts
  src/auth/dto/validate_user.dto.ts
  src/auth/local.strategy.ts
  src/session/session.controller.ts
  src/users/dto/register_user.dto.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: bug

#16 Apply Dockerfile, docker-compose.yml and .dockerignore for deployment
  .dockerignore
  Dockerfile
  docker-compose.yml
  src/main.ts
Labels: enhancement

#17 Create CircleCI config file for building checks and deployment
  .circleci/config.yml
Labels: enhancement

#18 Fix YML syntax
  .circleci/config.yml
Labels: bug

#22 Run npm audit fix
  package-lock.json
Labels: bug

#23 Mock user repository and write test cases for UsersService
  src/users/users.service.spec.ts
Labels: enhancement

#26 Create two unit tests for AuthService
  src/auth/auth.service.spec.ts
Labels: enhancement

#25 Create a test case for the method "register"
  src/users/users.controller.spec.ts
Labels: enhancement

#27 Make the response body of the route login empty
  src/session/session.controller.ts
Labels: bug

#28 Make register able to handle register's data conflict
  src/users/users.controller.spec.ts
  src/users/users.controller.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
  test/app.e2e-spec.ts
  test/users.e2e-spec.ts
Labels: enhancement

#29 Replace iuser with user
  src/users/users.service.spec.ts
Labels: enhancement

#30 Remove useless code
  src/users/users.service.spec.ts
Labels: enhancement

#32 Rename UsersService.findOne*
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/session/session.serializer.ts
  src/users/users.service.spec.ts
  src/users/users.service.ts
Labels: enhancement

#31 Feature/get session
  src/common/guards/authenticated.guard.ts
  src/session/session.controller.ts
Labels: enhancement

#34 Return unauthorized status when the user has logged in
  src/session/session.controller.ts
Labels: enhancement

#33 Create a route for project creation
  package-lock.json
  package.json
  src/common/pipes/validation.pipe.ts
  src/common/util/error-record-generator.ts
  src/projects/dto/create-project.dto.ts
  src/projects/projects.controller.spec.ts
  src/projects/projects.controller.ts
  src/projects/projects.entity.ts
  src/projects/projects.module.ts
  src/projects/projects.service.spec.ts
  src/projects/projects.service.ts
  src/tags/tags.module.ts
  src/tags/tags.service.spec.ts
  src/tags/tags.service.ts
Labels: enhancement

#37 Enhance cors
  src/main.ts
Labels: enhancement

#35 Rename to register-user.dto
  src/users/dto/register-user.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
  test/users.e2e-spec.ts
Labels: enhancement

#38 Fix docker-compose.yml to make the web app waiting for the database
  docker-compose.yml
Labels: bug

#39 Use enum for User.status and permission
  src/users/users.entity.ts
Labels: enhancement

#40 Re-revert "Create a route for project creation""
  package-lock.json
  package.json
  src/common/guards/authenticated.guard.ts
  src/common/pipes/validation.pipe.ts
  src/common/util/error-record-generator.ts
  src/projects/dto/create-project.dto.ts
  src/projects/projects.controller.spec.ts
  src/projects/projects.controller.ts
  src/projects/projects.entity.ts
  src/projects/projects.module.ts
  src/projects/projects.service.spec.ts
  src/projects/projects.service.ts
  src/tags/tags.module.ts
  src/tags/tags.service.spec.ts
  src/tags/tags.service.ts
Labels: enhancement

#42 Create a route for getting users' profile
  src/users/users.controller.ts
  src/users/users.entity.ts
Labels: enhancement

#41 Create a route for updaing users' profile
  src/common/pipes/id-validation.pipe.ts
  src/common/types/session-user.type.ts
  src/users/dto/update-profile.dto.ts
  src/users/users.controller.ts
  src/users/users.entity.ts
  src/users/users.service.ts
Labels: enhancement

#44 Remove a duplicated field
  src/users/users.entity.ts
Labels: bug

#49 Create a route for deleting a project
  src/common/types/operation-result.type.ts
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: enhancement

#47 Enable CORS credential
  src/main.ts
Labels: bug

#48 Make login route able to handle banned users
  src/auth/auth.service.ts
  src/auth/local.strategy.ts
  src/common/types/login-result.type.ts
Labels: enhancement

#46 Create a route for banning a user by the user's id
  src/common/guards/admin.guard.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: enhancement

#45 Create a route for reading a username by an Id
  src/users/users.controller.ts
Labels: enhancement

#51 Rename validate_user.dto.ts to validate-user.dto.ts
  src/auth/auth.service.ts
  src/auth/dto/validate-user.dto.ts
  src/auth/local.strategy.ts
  src/session/session.serializer.ts
Labels: enhancement

#52 Add CI status badget
  README.md
Labels: documentation

#53 Create bi-directional relationship between User and Project
  src/auth/dto/validate_user.dto.ts
  src/projects/projects.entity.ts
  src/users/users.entity.ts
Labels: enhancement

#55 Add a validator for RegisterUserDto
  src/users/dto/register-user.dto.ts
  src/users/users.controller.ts
Labels: enhancement

#56 Add a new field 'email' to UpdateProfileDto and make the route a 'PUT…
  src/users/dto/update-profile.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: bug

#57 Create a route for reading a user's all projects
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: enhancement

#58 Project creators should also involve the projects they created
  src/projects/projects.service.ts
Labels: bug

#59 Create a route for reading a project
  src/projects/dto/read-project.dto.ts
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: enhancement

#62 Create a route for updating a project
  src/common/types/operation-result.type.ts
  src/projects/dto/update-project.dto.ts
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
  src/tags/tags.service.ts
Labels: enhancement

#63 Add IsString and ArrayUnique to tags and change error messages
  src/projects/dto/create-project.dto.ts
Labels: bug

#64 Make admins able to see any project
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: bug

#65 Create a route for reading a project by its name and its owner's username
  src/common/pipes/query-string.validation.pipe.ts
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: enhancement

#66 Create a route for transfering a project to other member in this project
  src/common/types/resource.type.ts
  src/projects/dto/transfer-project.dto.ts
  src/projects/projects.controller.ts
  src/projects/projects.module.ts
  src/projects/projects.service.ts
Labels: enhancement

#67 Create a route for changing a project's privacy
  src/projects/dto/privacy-project.dto.ts
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: enhancement

#68 Create a route for adding a new member to a project
  src/projects/dto/member-id.dto.ts
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: enhancement

#69 Create a route for reading all member from a project
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: enhancement

#70 Create a route for removing a member from a project
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: enhancement

#71 Create ReadProfileDto for the route of reading a profile and add field 'status'
  src/users/dto/read-profile.dto.ts
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: enhancement

#72 Create a new entity Label
  src/app.module.ts
  src/labels/labels.entity.ts
  src/labels/labels.module.ts
  src/projects/projects.entity.ts
Labels: enhancement

#73 Change DTO constraints
  src/auth/auth.service.ts
  src/projects/dto/create-project.dto.ts
  src/projects/dto/update-project.dto.ts
  src/users/dto/register-user.dto.ts
  src/users/dto/update-profile.dto.ts
Labels: bug

#74 Remove the length defition of Label entity
  src/labels/labels.entity.ts
Labels: enhancement

#75 Create a route for adding a new label for a project
  src/labels/dto/create-label.dto.ts
  src/labels/labels.module.ts
  src/labels/labels.service.spec.ts
  src/labels/labels.service.ts
  src/projects/dto/labels/create-label.dto.ts
  src/projects/projects.controller.ts
  src/projects/projects.module.ts
  src/projects/projects.service.ts
Labels: enhancement

#76 The composite unique condition is of name and project id
  src/labels/labels.service.ts
Labels: bug

#77 Create a route for reading all labels of a project
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: enhancement

#78 Create a route for reading a label by its id
  src/labels/dto/read-label.dto.ts
  src/labels/labels.controller.spec.ts
  src/labels/labels.controller.ts
  src/labels/labels.module.ts
  src/labels/labels.service.ts
Labels: enhancement

#79 Create a route for updating a label by its id
  src/labels/dto/update-label.dto.ts
  src/labels/labels.controller.ts
  src/labels/labels.module.ts
  src/labels/labels.service.ts
  src/projects/projects.module.ts
Labels: enhancement

#80 Create a route for removing a label by its id
  src/labels/labels.controller.ts
  src/labels/labels.service.ts
Labels: enhancement

#81 Apply error messages and refactor some code a little
  src/auth/local.strategy.ts
  src/common/guards/admin.guard.ts
  src/common/guards/authenticated.guard.ts
  src/common/pipes/id-validation.pipe.ts
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
  src/users/users.controller.ts
Labels: bug

#82 Create the new entity Issue
  src/app.module.ts
  src/issues/issues.entity.ts
  src/issues/issues.module.ts
  src/labels/labels.entity.ts
  src/projects/projects.entity.ts
  src/users/users.entity.ts
Labels: enhancement

#83 Create the new entity Comment
  src/app.module.ts
  src/comments/comments.entity.ts
  src/comments/comments.module.ts
  src/issues/issues.entity.ts
  src/users/users.entity.ts
Labels: enhancement

#84 Create a route for creating a new issue of a project
  src/comments/comments.entity.ts
  src/comments/comments.module.ts
  src/comments/comments.service.spec.ts
  src/comments/comments.service.ts
  src/comments/dto/create-comment.dto.ts
  src/common/util/error-record-generator.ts
  src/issues/dto/create-issue.dto.ts
  src/issues/issues.entity.ts
  src/issues/issues.module.ts
  src/issues/issues.service.spec.ts
  src/issues/issues.service.ts
  src/labels/labels.service.ts
  src/projects/dto/issues/create-issue.dto.ts
  src/projects/projects.controller.ts
  src/projects/projects.module.ts
  src/projects/projects.service.ts
Labels: enhancement

#85 Create a route for reading all issue ids of a project
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
Labels: enhancement

#86 Create a route for reading an issue by id
  src/issues/dto/read-issue.dto.ts
  src/issues/issues.controller.spec.ts
  src/issues/issues.controller.ts
  src/issues/issues.module.ts
  src/issues/issues.service.ts
Labels: enhancement

#89 Create a route for updating a issue
  src/issues/dto/update-issue.dto.ts
  src/issues/issues.controller.ts
  src/issues/issues.service.ts
Labels: enhancement

#90 Create a route for closing an issue
  src/issues/issues.controller.ts
  src/issues/issues.entity.ts
  src/issues/issues.service.ts
Labels: enhancement

#91 Create a route for reading all issues that the user involves
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: enhancement

#93 Create a new comment of an issue
  src/issues/dto/create-comment.dto.ts
  src/issues/issues.controller.ts
  src/issues/issues.service.ts
Labels: enhancement

#94 Create a route for reading all comment ids of an issue
  src/issues/issues.controller.ts
  src/issues/issues.service.ts
Labels: enhancement

#95 Add the new field 'ownerId' to ReadProjectDto
  src/projects/dto/read-project.dto.ts
  src/projects/projects.service.ts
Labels: enhancement

#96 Create a route for reading a comment by its id
  src/comments/comments.controller.spec.ts
  src/comments/comments.controller.ts
  src/comments/comments.module.ts
  src/comments/comments.service.ts
  src/comments/dto/read-comment.dto.ts
Labels: enhancement

#88 Put the repo name on README.md
  README.md
Labels: documentation

#97 Create a route for updating a comment by its id
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
  src/comments/dto/update-comment.dto.ts
Labels: enhancement

#99 Add the field 'status' in ReadIssueDto
  src/issues/dto/read-issue.dto.ts
  src/issues/issues.controller.ts
  src/issues/issues.service.ts
Labels: bug

#100 Create a route for updating a comment's status by id
  src/comments/comments.controller.ts
  src/comments/comments.service.ts
  src/comments/dto/update-comment-status.dto.ts
Labels: enhancement

#101 Search projects by a name
  src/app.module.ts
  src/projects/projects.service.ts
  src/query/dto/query-project.dto.ts
  src/query/query.controller.spec.ts
  src/query/query.controller.ts
  src/query/query.module.ts
Labels: enhancement

#103 Search issues by title
  src/issues/issues.service.ts
  src/query/dto/query-issue.dto.ts
  src/query/query.controller.ts
  src/query/query.module.ts
Labels: enhancement

#104 Create the new field lineToken
  src/users/users.entity.ts
Labels: enhancement

#105 Create the new field 'lineToken'
  src/users/dto/read-profile.dto.ts
  src/users/dto/update-profile.dto.ts
  src/users/users.service.ts
Labels: enhancement

#106 Apply argon2 to passwords
  package-lock.json
  package.json
  src/auth/auth.service.ts
  src/users/users.service.ts
Labels: enhancement

#107 Handle LINE tokens
  src/users/users.service.ts
Labels: enhancement

#108 Apply LINE notification
  package.json
  src/app.module.ts
  src/common/pipes/insight-query.validation.pipe.ts
  src/issues/issues.module.ts
  src/issues/issues.service.ts
  src/labels/labels.service.ts
  src/notifier/notifier.module.ts
  src/notifier/notifier.service.spec.ts
  src/notifier/notifier.service.ts
  src/projects/projects.module.ts
  src/projects/projects.service.ts
  src/users/dto/insight-query.dto.ts
  src/users/dto/insight-report.dto.ts
  src/users/users.service.ts
Labels: enhancement

#109 Fix filter
  src/users/users.service.ts
Labels: enhancement
